### ISSUE TITLE
Docker process is hanging after test execution

### ISSUE THREAD

**Issue by AlexeyCL** [stsvilik/wdio-docker-service#91] opened 2020-12-27 13:02 UTC
Hi,
I'm facing an issue with the docker service:

Config of WebdriverIO
```
exports.config = {

    runner: 'local',

    specs: [
        './test/specs/**/*.js'
    ],
    exclude: [
    ],
    
    maxInstances: 10,
   
    capabilities: [
        {
            browserName: 'chrome',
            acceptInsecureCerts: true,
            'goog:chromeOptions': {
                args: ['--window-size=1920,1080', '--incognito', '-–ignore-certificate-errors', '--headless'],
            },
        },
    ],
    logLevel: 'info',
    bail: 0,
    baseUrl: 'http://localhost',
    
    waitforTimeout: 10000,

    connectionRetryTimeout: 120000,

    connectionRetryCount: 3,
    dockerOptions: {
        image: 'selenium/standalone-chrome',
        healthCheck: 'http://localhost:4444',
        options: {
            p: ['4444:4444'],
            shmSize: '2g'
        }
    },
    services: ['docker'],
    reporters: ['spec'],
    mochaOpts: {
        ui: 'bdd',
        timeout: 60000
    },
}
```
**Bug description:**

For test execution, I'm using lerna, which executes tests with a docker. After the test execution, the docker process is stuck.
> 61549 ttys001    0:00.09 /usr/local/bin/node /Users/alexeykagansky/dev/wdio-docker-lerna/node_modules/wdio-docker-service/lib/modules/dockerEvents

To Reproduce
https://github.com/AlexeyCL/wdio-docker-lerna you can find a simple example

**Comment by stsvilik** [comment] 2020-12-28 06:03
@AlexeyCL I would first try to remove `selenium/standalone-chrome` image from your system, to force pulling latest version. I've had issues with that before. It's pretty easy in command line `docker rmi selenium/standalone-chrome`.

**Comment by AlexeyCL** [comment] 2020-12-28 07:03
hey @stsvilik ,
but it happens in CI, also I don't have `selenium/standalone-chrome` image, it runs in CI, without anything

**Comment by AlexeyCL** [comment] 2020-12-28 07:07
@stsvilik well, I removed all images and it happened( Could you please try to run it from the example, that I provided?

**Comment by stsvilik** [comment] 2020-12-28 07:09
Perhaps the issue is with lerna test runner which is unable to terminate dockers process. Mocha seems to be able to terminate the container just fine.

**Comment by AlexeyCL** [comment] 2020-12-28 07:13
I think, the problem not with Lerna, I tried another executor and got the same issue. I'm trying to find another example

**Comment by AlexeyCL** [comment] 2020-12-28 10:11
@stsvilik please review https://github.com/stsvilik/wdio-docker-service/pull/93

**Comment by stsvilik** [comment] 2020-12-29 15:03
@AlexeyCL I have merged your PR (Thank you!) and upgraded all dependencies on top of it. Please install latest version 3.1.0.

**Closed by stsvilik** 2020-12-29 15:03 UTC

**Comment by stsvilik** [comment] 2020-12-29 21:27
@AlexeyCL please let me know if this fixed your issue
